# Generated by Django 5.1.7 on 2025-03-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('views', models.IntegerField()),
                ('rating', models.FloatField()),
                ('crm', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('conditions', models.TextField()),
                ('patient_groups', models.CharField(max_length=255)),
                ('insurance', models.CharField(max_length=100)),
                ('follow_up', models.CharField(max_length=100)),
                ('experience', models.TextField()),
                ('education', models.JSONField()),
                ('video_url', models.URLField()),
                ('consultation_fee', models.FloatField()),
                ('additional_data', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
